CREATE TABLE books (
    book_id INTEGER PRIMARY KEY generated by default as identity,
    title VARCHAR(255),
    publication_year INTEGER,
    in_stock BOOLEAN default TRUE,
    author_id INTEGER references authors(author_id)
);